added the sampler as a config feature
TykTechnologies/opentelemetry pull request #16
Opened 2023-07-10 19:11 UTC by sredxny

## Description

## Related Issue

## Motivation and Context

## Test Coverage For This Change

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)
- [ ] Documentation updates or improvements.

## Checklist

- [ ] I have [reviewed the guidelines](./CONTRIBUTING.md) for contributing to this repository.
- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [ ] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
     - [ ] I have manually updated the README(s)/documentation accordingly.
     - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
    - [ ] `gofmt -s -w .`
    - [ ] `go vet ./...`

2023-07-13 07:06 UTC, tbuchaillot requested changes
@sredxny requested some changes. Also linter + tests are failing.

2023-07-13 07:06 UTC, tbuchaillot commented on config/config.go
> +	SamplingType string `json:"sampler_type"`
@sredxny what do you think about moving Sampling related config to a separated config structure?

2023-07-13 07:06 UTC, tbuchaillot commented on trace/provider.go
> +	case config.ALWAYSON:
@sredxny do you think it's worth to lower the string and compare here? I can see a lot of user errors setting `alwayson` instead of `AlwaysOn`

2023-07-13 12:20 UTC, mativm02 requested changes

2023-07-13 12:20 UTC, mativm02 commented on config/config.go
> +	SamplingType string `json:"sampler_type"`
@sredxny also, I would keep the same field name and JSON tag:
`SamplerType` & `sampler_type` - IIRC env vars are generated from the struct fields and could create some confusion

2023-07-13 21:32 UTC, mativm02 approved these changes
lgtm!

2023-07-14 07:25 UTC, tbuchaillot requested changes

2023-07-14 07:25 UTC, tbuchaillot commented on config/config.go
> +	SamplerType string `json:"sampler_type"`
@sredxny let's avoid double naming in the `sampling` variables. It could be `type`, `rate`, and `parent_based`.

2023-07-14 07:27 UTC, tbuchaillot commented on config/config.go
> +		c.Sampling.SamplingRate = 0.5
@sredxny why do we need to set the sampling rate to 0.5 by default if the default type is ALWAYSON? shouldn't we check if it's ratio based to set it?

2023-07-14 13:08 UTC, sredxny commented on config/config.go
> +		c.Sampling.SamplingRate = 0.5
@tbuchaillot both options will work, it happens that if you set 0.5 and AlwaysOn then the 0.5 is ignored.. However let me update that

2023-07-14 13:59 UTC, tbuchaillot approved these changes

2023-07-14 14:18 UTC, merged