Parsing endpoint in HTTP client
TykTechnologies/opentelemetry pull request #17
Opened 2023-07-11 13:32 UTC by mativm02

## Description

## Related Issue

## Motivation and Context

## Test Coverage For This Change

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)
- [ ] Documentation updates or improvements.

## Checklist

- [ ] I have [reviewed the guidelines](./CONTRIBUTING.md) for contributing to this repository.
- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [ ] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
     - [ ] I have manually updated the README(s)/documentation accordingly.
     - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
    - [ ] `gofmt -s -w .`
    - [ ] `go vet ./...`

2023-07-13 17:49 UTC, sredxny requested changes

2023-07-13 17:49 UTC, sredxny commented on e2e/basic/basic.go
> +	provider, err := trace.NewProvider(trace.WithContext(ctx), trace.WithConfig(&cfg), trace.WithLogger(logrus.New()))
why are you setting the logger here? I think it should be passed from the consumer app (gw, mdcb etc)

2023-07-13 17:49 UTC, sredxny commented on trace/exporter.go
> +	}
what do you think about work this conditional in positive:

```
if cfg.TLSCOnfig.Enable{
}else{
// no tls
}
```

2023-07-13 17:49 UTC, sredxny commented on trace/exporter.go
> +	}
same here, make it `if cfg.TLSCOnfig.Enable{`

2023-07-14 11:49 UTC, mativm02 commented on e2e/basic/basic.go
> +	provider, err := trace.NewProvider(trace.WithContext(ctx), trace.WithConfig(&cfg), trace.WithLogger(logrus.New()))
@sredxny it's the basic.go app :) it's the application we're using for e2e testing, I think it would be nice to log if something occurs (also it helps me to test stuff quickly)

2023-07-14 11:50 UTC, mativm02 commented on trace/exporter.go
> +	}
@sredxny in most cases TLSConfig will be disabled (it's the default value) - I think if we keep it as it is right now, we'll be saving one conditional check in most cases, wdyt?

2023-07-14 13:59 UTC, tbuchaillot approved these changes

2023-07-14 13:59 UTC, tbuchaillot commented on config/config.go
> +	TLSConfig TLSConfig `json:"tls_config"`
@mativm02 let's change the config to `tls`

2023-07-17 13:47 UTC, sredxny commented on trace/exporter.go
> +	}
I see your point, then why not do something like:

```
isTLSDisabled := !cfg.TLSConfig.Enable

if isTLSDisabled{
}else{
}
```

2023-07-17 14:19 UTC, mativm02 commented on trace/exporter.go
> +	}
@sredxny done, thx!

2023-07-17 14:32 UTC, sredxny approved these changes

2023-07-18 15:53 UTC, merged